<#
.SYNOPSIS
    Prepare a task-local OpenCode command for a Windows Herdr workspace.

.DESCRIPTION
    PowerShell command discovery can select opencode.ps1 when Herdr starts
    OpenCode through Start-Process. That wrapper is not a runnable Win32 image
    for the Herdr adapter. This helper never edits the global installation or
    the persistent PATH. It creates a unique temporary directory containing an
    opencode.cmd shim and prints the environment value to pass to
    `herdr workspace create --env PATH=...`.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[A-Za-z0-9._-]+$')]
    [string]$TaskId,

    [string]$TargetPath,

    [switch]$SetCurrentProcessPath
)

$ErrorActionPreference = 'Stop'

if ($env:OS -ne 'Windows_NT') {
    throw 'prepare-opencode-windows.ps1 is only supported on Windows.'
}

function Resolve-OpenCodeTarget {
    param([string]$ExplicitPath)

    if ($ExplicitPath) {
        $item = Get-Item -LiteralPath $ExplicitPath -ErrorAction Stop
        if (-not $item.PSIsContainer -and $item.Extension.ToLowerInvariant() -in @('.cmd', '.exe')) {
            return $item.FullName
        }
        throw "TargetPath must point to an existing .cmd or .exe file: $ExplicitPath"
    }

    $candidates = @()
    foreach ($name in @('opencode.cmd', 'opencode.exe')) {
        $candidates += @(Get-Command $name -CommandType Application -All -ErrorAction SilentlyContinue |
            ForEach-Object { $_.Source } |
            Where-Object { $_ -and (Test-Path -LiteralPath $_ -PathType Leaf) })
    }

    # When only opencode.ps1 is visible, prefer the sibling .cmd generated by
    # npm rather than allowing Herdr/Start-Process to select the .ps1 wrapper.
    if (-not $candidates) {
        $ps1 = Get-Command opencode.ps1 -CommandType ExternalScript -All -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($ps1) {
            $sibling = Join-Path (Split-Path -Parent $ps1.Source) 'opencode.cmd'
            if (Test-Path -LiteralPath $sibling -PathType Leaf) {
                $candidates += (Get-Item -LiteralPath $sibling).FullName
            }
        }
    }

    $target = $candidates |
        Sort-Object { if ([IO.Path]::GetExtension($_).ToLowerInvariant() -eq '.cmd') { 0 } else { 1 } }, Length |
        Select-Object -First 1
    if (-not $target) {
        throw 'Could not resolve a runnable opencode.cmd or opencode.exe without using opencode.ps1.'
    }
    return (Get-Item -LiteralPath $target -ErrorAction Stop).FullName
}

$target = Resolve-OpenCodeTarget -ExplicitPath $TargetPath
$tempRoot = [IO.Path]::GetTempPath()
$shimDirectory = Join-Path $tempRoot ("herdr-opencode-{0}-{1}" -f $TaskId, ([guid]::NewGuid().ToString('N')))
New-Item -ItemType Directory -Path $shimDirectory -Force | Out-Null

$shimPath = Join-Path $shimDirectory 'opencode.cmd'
$quotedTarget = $target.Replace('"', '\"')
if ([IO.Path]::GetExtension($target).ToLowerInvariant() -eq '.cmd') {
    $shim = @"
@echo off
call "$quotedTarget" %*
exit /b %errorlevel%
"@
} else {
    $shim = @"
@echo off
"$quotedTarget" %*
exit /b %errorlevel%
"@
}
Set-Content -LiteralPath $shimPath -Value $shim.TrimStart() -Encoding ASCII

$effectivePath = "$shimDirectory;$env:PATH"
if ($SetCurrentProcessPath) {
    # This changes only the calling PowerShell process and its children.
    $env:PATH = $effectivePath
}

[pscustomobject]@{
    task_id = $TaskId
    target = $target
    shim_directory = $shimDirectory
    shim = $shimPath
    path = $effectivePath
    process_path_changed = [bool]$SetCurrentProcessPath
} | ConvertTo-Json -Compress
